<?php 
return array (
    'Default'=>array(
	    'allow'=>RBAC_EVERYONE,
    ),
    'Spm'=>array(
        'allow'=>RBAC_HAS_ROLE,
        'actions'=>array(
	        'Index'=>array('allow'=>'sysadmin'),
            'Add'=>array('allow'=>'sysadmin'),
            'Delete'=>array('allow'=>'sysadmin'),
            'Modify'=>array('allow'=>'sysadmin')  
	        )
    ),
    'Scm'=>array(
        'allow'=>RBAC_HAS_ROLE,
        'actions'=>array(
	        'Index'=>array('allow'=>'sysadmin',),
	        'Add'=>array('allow'=>'sysadmin',),
	        'Modify'=>array('allow'=>'sysadmin',),
	        'Delete'=>array('allow'=>'sysadmin',),
	        ),
    ),
    'Server'=>array(
        'allow'=>RBAC_HAS_ROLE,
        'actions'=>array(
            'Index'=>array('allow'=>'sysadmin',),
            'Add'=>array('allow'=>'sysadmin',),
            'Modify'=>array('allow'=>'sysadmin',),
            'Delete'=>array('allow'=>'sysadmin',),
            ),
    ),
    'Som'=>array(
        'allow'=>RBAC_HAS_ROLE,
        'actions'=>array(
            'Index'=>array('allow'=>'sysadmin',),
            'Add'=>array('allow'=>'sysadmin',),
            'Modify'=>array('allow'=>'sysadmin',),
            'Delete'=>array('allow'=>'sysadmin',),
            ),
    ),
    'Saler'=>array(
        'allow'=>RBAC_HAS_ROLE,
        'actions'=>array(
            'Index'=>array('allow'=>'sysadmin',),
            'Add'=>array('allow'=>'sysadmin',),
            'Modify'=>array('allow'=>'sysadmin',),
            'Delete'=>array('allow'=>'sysadmin',),
            ),
    ),
	'User'=>array(
		'allow'=>RBAC_HAS_ROLE,
			'actions'=>array(
			'AddUser'=>array('allow'=>'User',),
			'SaveUser'=>array('allow'=>'User',),
			'ListUser'=>array('allow'=>'User',),
			'UpdatePassword'=>array('allow'=>'User',),
			'EditUser'=>array('allow'=>'User',),
			'DelUser'=>array('allow'=>'User',),
		),
	),
	'Role'=>array(
		'allow'=>'sysadmin',
		'actions'=>array(
		),
	),
	'Prem'=>array(
		'allow'=>'sysadmin',
		'actions'=>array(
			'AddCtl'=>array('allow'=>'sysadmin',),
			'AddAct'=>array('allow'=>'sysadmin',),
		)
	),

)
?>