<?php
return array (
  'index_Default' => 'RBAC_EVERYONE',
  'index_Default_Upload' => 'RBAC_EVERYONE',
  'index_Default_VerifyCode' => 'RBAC_EVERYONE',
  'index_Index' => 'RBAC_ONLY',
  'index_Index_Index' => 'RBAC_ONLY',
  'index_Index_Left' => 'RBAC_ONLY',
  'index_Index_Main' => 'RBAC_ONLY',
  'index_Index_Top' => 'RBAC_ONLY',
  'index_Index_Bottom' => 'RBAC_ONLY',
  'index_Index_Login' => 'RBAC_EVERYONE',
  'index_Index_LoginOut' => 'RBAC_EVERYONE',
  'index_News' => '',
  'index_News_Index' => '',
  'index_News_Add' => '',
  'index_News_Edit' => '',
  'index_News_Del' => '',
  'index_Games' => '',
  'index_Games_Index' => '',
  'index_Games_Add' => '',
  'index_Games_Edit' => '',
  'index_Games_Del' => '',
  'index_Servers' => '',
  'index_Servers_Index' => '',
  'index_Servers_Add' => '',
  'index_Servers_Edit' => '',
  'index_Servers_Del' => '',
  'index_Servers_CreateCache' => '',
)
?>