<?php
return array(
	'index_Default'=>array(
		'name'=>'默认所需要的模块',
		'display'=>false,
		'child'=>array(
			'index_Default_Upload'=>array('name'=>'kindeditor上传图片','display'=>false),
			'index_Default_VerifyCode'=>array('name'=>'验证码','display'=>false),
		),
	),

	'index_Index'=>array(
		'name'=>'默认显示模块',
		'display'=>false,
		'child'=>array(
			'index_Index_Index'=>array('name'=>'主显示页面','display'=>false),
			'index_Index_Left'=>array('name'=>'右侧菜单','display'=>false),
			'index_Index_Main'=>array('name'=>'主显示页面','display'=>false),
			'index_Index_Top'=>array('name'=>'顶部显示','display'=>false),
			'index_Index_Bottom'=>array('name'=>'底部显示页面','display'=>false),
			'index_Index_Login'=>array('name'=>'登陆','display'=>false),
			'index_Index_LoginOut'=>array('name'=>'退出登录','display'=>false),
		),
	),
	'index_News'=>array(
		'name'=>'资讯管理',
		'display'=>true,
		'child'=>array(
			'index_News_Index'=>array('name'=>'资讯显示列表','display'=>true),
			'index_News_Add'=>array('name'=>'增加资讯','display'=>true),
			'index_News_Edit'=>array('name'=>'编辑资讯','display'=>false),
			'index_News_Del'=>array('name'=>'删除资讯','display'=>false),
		),
	),
	'index_Games'=>array(
		'name'=>'游戏管理',
		'display'=>true,
		'child'=>array(
			'index_Games_Index'=>array('name'=>'游戏列表','display'=>true),
			'index_Games_Add'=>array('name'=>'增加游戏','display'=>true),
			'index_Games_Edit'=>array('name'=>'编辑游戏','display'=>false),
			'index_Games_Del'=>array('name'=>'删除游戏','display'=>false),
			'index_Games_Sortinfo'=>array('name'=>'更新游戏排序','display'=>false),
			'index_Games_CreateCache'=>array('name'=>'创建缓存','display'=>true),
		),
	),
	
	'index_Servers'=>array(
		'name'=>'游戏服务器管理',
		'display'=>true,
		'child'=>array(
			'index_Servers_Index'=>array('name'=>'服务器列表','display'=>true),
			'index_Servers_Add'=>array('name'=>'增加服务器','display'=>true),
			'index_Servers_Edit'=>array('name'=>'编辑服务器','display'=>false),
			'index_Servers_Del'=>array('name'=>'删除服务器','display'=>false),
			'index_Servers_CreateCache'=>array('name'=>'创建缓存','display'=>true),
		),
	),
);