<?php
return array(
	'setup_Prem'=>array(
		'name'=>'权限设置',
		'display'=>true,
		'child'=>array(
			'setup_Prem_ModuleIndex'=>array('name'=>'权限管理页面','display'=>true),
			'setup_Prem_ModuleEdit'=>array('name'=>'编辑权限模块','display'=>false),
			'setup_Prem_ModuleAdd'=>array('name'=>'增加模块','display'=>false),
			'setup_Prem_ModuleDel'=>array('name'=>'删除模块','display'=>false),
			'setup_Prem_ActionsIndex'=>array('name'=>'模块方法列表','display'=>false),
			'setup_Prem_ActionEdit'=>array('name'=>'编辑方法','display'=>false),
			'setup_Prem_RoleDel'=>array('name'=>'删除角色','display'=>false),
			'setup_Prem_RoleEdit'=>array('name'=>'编辑角色','display'=>false),
			'setup_Prem_RoleAdd'=>array('name'=>'增加角色','display'=>false),
			'setup_Prem_RoleIndex'=>array('name'=>'角色列表','display'=>true),
			'setup_Prem_RoleAct'=>array('name'=>'角色权限编辑','display'=>false),
			'setup_Prem_ModelCache'=>array('name'=>'创建模块缓存','display'=>false),
		),
	),
	'setup_System'=>array(
		'name'=>'系统设置',
		'display'=>true,
		'child'=>array(
			'setup_System_Index'=>array('name'=>'系统设置列表','display'=>true),
		),
	),
	'setup_User'=>array(
		'name'=>'用户管理',
		'display'=>true,
		'child'=>array(
			'setup_User_Index'=>array('name'=>'用户列表','display'=>true),
			'setup_User_Add'=>array('name'=>'增加用户','display'=>true),
			'setup_User_Edit'=>array('name'=>'编辑用户','display'=>false),
			'setup_User_Del'=>array('name'=>'删除用户','display'=>false),
			'setup_User_CreateCache'=>array('name'=>'创建用户缓存','display'=>true),
		),
	),
);